'use strict';
const $=s=>document.querySelector(s);
const token=$('meta[name="studio-token"]').content;
let versions=[],doc=null,group='',mode='form',changes={},sourceDirty=false,busy=false,page=1;
const icon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h10l4 4v14H5zM15 3v5h4M8 12h8M8 16h6"/></svg>';
function error(message){$('#error span').textContent=message;$('#error').hidden=false;}
function dirty(){return Object.keys(changes).length>0||sourceDirty;}
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-Studio-Token':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'操作失败，请重试。');return data;}
function artifact(file){return '/api/artifact?'+new URLSearchParams({id:doc.preview.id,file,token});}
function status(message){$('#save-state').textContent=message|| (dirty()?'有未保存的修改':'已保存到本机');$('#save-state').classList.toggle('dirty',dirty());$('#save').disabled=busy||!dirty();$('#generate').disabled=busy||!doc;$('#empty-generate').disabled=busy||!doc;$('#reload').disabled=busy;$('#form-mode').disabled=busy;$('#source-mode').disabled=busy;$('#search').disabled=busy;document.querySelectorAll('.version,#fields input,#fields textarea,#source').forEach(el=>el.disabled=busy);if(doc?.preview){const stale=dirty()||doc.preview.revision!==doc.revision;$('#preview-state').textContent=stale?'内容有修改 · 待生成':'已与保存内容同步';$('#download').firstChild.textContent=stale?'下载上次 PDF':'下载 PDF';}}
function setBusy(value,message){busy=value;status(message);$('#generate span').textContent=value?'正在处理…':'保存并生成 PDF';}
function list(){const nav=$('#versions');nav.replaceChildren();const term=$('#search').value.trim().toLowerCase();let last=null,count=0;for(const v of versions){if(![v.name,v.id,v.detail].join(' ').toLowerCase().includes(term))continue;const kind=v.public?'公开版本':'私人版本';if(last!==kind){const h=document.createElement('p');h.className='version-group';h.textContent=kind;nav.append(h);last=kind;}const b=document.createElement('button');b.className='version';b.innerHTML=icon+'<span><strong></strong><small></small></span>';b.querySelector('strong').textContent=v.name;b.querySelector('small').textContent=v.public?v.detail:v.id.replace(/^resume_/, '').replaceAll('_', ' · ');b.title=v.name+' · '+v.id;b.setAttribute('aria-current',String(v.id===doc?.version));b.disabled=busy;b.onclick=()=>choose(v.id);nav.append(b);count++;}if(!count){const p=document.createElement('p');p.className='rail-loading';p.textContent='没有匹配的版本。';nav.append(p);}$('#version-count').textContent=versions.length;}
function tabs(){const nav=$('#sections');nav.replaceChildren();for(const g of [...new Set(doc.fields.map(f=>f.group))]){const b=document.createElement('button');b.type='button';b.textContent=g;b.setAttribute('aria-current',String(g===group));b.onclick=()=>{group=g;tabs();fields();$('.editor-scroll').scrollTop=0;};nav.append(b);}}
function fields(){const form=$('#fields');form.replaceChildren();const items=doc.fields.filter(f=>f.group===group);const header=document.createElement('div');header.className='section-title';const h=document.createElement('h3');h.textContent=group;const c=document.createElement('span');c.textContent=items.length+' 项';header.append(h,c);form.append(header);let context='';items.forEach((f,i)=>{if(f.context&&f.context!==context){const h=document.createElement('h4');h.className='entry-title';h.textContent=f.context;form.append(h);context=f.context;}const label=document.createElement('label');label.className='field';const text=document.createElement('span');text.textContent=f.label;const input=document.createElement(f.multiline?'textarea':'input');input.value=Object.hasOwn(changes,f.id)?changes[f.id]:f.value;input.id='field-'+i;input.name=f.id;if(f.multiline)input.rows=Math.min(8,Math.max(3,Math.ceil(input.value.length/34)));input.classList.toggle('changed',Object.hasOwn(changes,f.id));input.oninput=()=>{if(input.value===f.value)delete changes[f.id];else changes[f.id]=input.value;input.classList.toggle('changed',Object.hasOwn(changes,f.id));status();};label.append(text,input);form.append(label);});$('#field-count').textContent=doc.fields.length+' 个可编辑字段';}
function fill(){const v=versions.find(v=>v.id===doc.version);$('#document-title').textContent=v?.name||doc.name;$('#scope-note').textContent=doc.public?'公开内容源 · 修改共享文本可能影响其他引用，保存不会发布到网站。':'私人版本 · 修改仅覆盖当前版本，共享内容保持不变。';const groups=[...new Set(doc.fields.map(f=>f.group))];if(!groups.includes(group))group=groups[0];$('#source').value=doc.source;list();tabs();fields();showMode();proof();status();}
function showMode(){const source=mode==='source';$('#fields').hidden=source;$('#sections').hidden=source;$('#source-pane').hidden=!source;$('#form-mode').setAttribute('aria-pressed',String(!source));$('#source-mode').setAttribute('aria-pressed',String(source));}
async function choose(version){if(busy||version===doc?.version)return;if(dirty()&&!confirm('当前修改尚未保存。放弃修改并切换版本？'))return;setBusy(true,'正在载入版本…');$('#error').hidden=true;try{const next=await api('document?version='+encodeURIComponent(version));doc=next;changes={};sourceDirty=false;page=1;group='';fill();}catch(e){error(e.message);}finally{setBusy(false,doc?'已载入本机内容':'请重新载入');}}
function proof(){const p=doc?.preview;$('#empty-preview').hidden=!!p;$('#page').hidden=!p;$('#download').hidden=!p;if(!p){$('#page-count').textContent='— / —';$('#preview-state').textContent='尚未生成';$('#prev').disabled=$('#next').disabled=true;return;}page=Math.min(page,p.pages);$('#page-image').src=artifact('page-'+page+'.png');$('#page-image').alt=doc.name+'的简历 PDF，第 '+page+' 页';$('#page-count').textContent=page+' / '+p.pages;$('#page-caption').textContent='第 '+page+' 页，共 '+p.pages+' 页';$('#prev').disabled=page<=1;$('#next').disabled=page>=p.pages;$('#download').href=artifact('document.pdf');$('#download').download=doc.version+'.pdf';status();}
async function save(){if(!dirty())return;const body={version:doc.version,revision:doc.revision,...(mode==='source'?{source:$('#source').value}:{changes})};doc=await api('save',body);changes={};sourceDirty=false;fill();}
async function action(render){if(busy||!doc)return;$('#error').hidden=true;setBusy(true,render?'正在保存并排版…':'正在保存…');try{await save();if(render){$('#rendering').hidden=false;const generated=await api('render',{version:doc.version,revision:doc.revision});doc.preview=generated;page=1;proof();}status();}catch(e){error(e.message);}finally{$('#rendering').hidden=true;setBusy(false);}}
$('#save').onclick=()=>action(false);$('#generate').onclick=$('#empty-generate').onclick=()=>action(true);$('#search').oninput=list;
$('#reload').onclick=async()=>{if(busy)return;if(dirty()&&!confirm('重新载入会放弃当前未保存修改，是否继续？'))return;const version=doc?.version||'public-zh';changes={};sourceDirty=false;doc=null;await choose(version);};
$('#form-mode').onclick=()=>switchMode('form');$('#source-mode').onclick=()=>switchMode('source');
function switchMode(next){if(next===mode)return;if(dirty()){error('请先保存当前修改，再切换编辑方式。也可重新载入以放弃修改。');return;}mode=next;showMode();}
$('#source').oninput=()=>{sourceDirty=$('#source').value!==doc.source;status();};
$('#prev').onclick=()=>{if(page>1){page--;proof();$('#proof-canvas').scrollTop=0;}};$('#next').onclick=()=>{if(page<doc.preview.pages){page++;proof();$('#proof-canvas').scrollTop=0;}};
$('#page-image').onerror=()=>error('预览图片读取失败，请重新生成 PDF。');$('#error button').onclick=()=>$('#error').hidden=true;$('#fields').onsubmit=e=>e.preventDefault();
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('.workspace').classList.toggle('show-preview',b.dataset.view==='preview');});
window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue='';}});window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();action(false);}});
(async()=>{try{versions=await api('versions');list();await choose('public-zh');}catch(e){error(e.message);status('连接失败，请重新启动工作台');}})();
